name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Changes
  $CHANGES
categories:
  - title: "🚀 Features"
    labels:
      - enhancement
  - title: "🧰 Maintenance"
    labels:
      - automation
      - chore
      - ci
  - title: "📝 Documentation"
    labels:
      - documentation
  - title: "🐛 Fixes"
    labels:
      - bug
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No user-facing changes.'
release-name-template: 'CADMU v$NEXT_PATCH_VERSION'
prerelease: false
